import { MigrationInterface, QueryRunner } from "typeorm";

export class AddNotificacionExtensionColumn1783121726461 implements MigrationInterface {
    name = 'AddNotificacionExtensionColumn1783121726461'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "servicios" ADD "notificacion_extension_enviada" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`DROP INDEX "public"."empleada_fotos_empleada_id_orden_key"`);
        await queryRunner.query(`ALTER TABLE "empleada_fotos" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "empleada_fotos" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "empleada_fotos" ALTER COLUMN "orden" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "extensiones_servicio" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "extensiones_servicio" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "extras_servicio" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "extras_servicio" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "prorrogas" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "prorrogas" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "viajes" DROP CONSTRAINT "FK_f277fcfb42bf3b6a67bb0281e7b"`);
        await queryRunner.query(`ALTER TABLE "choferes" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "choferes" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "viajes" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "viajes" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "extensiones_servicio" DROP CONSTRAINT "FK_27b5b99c53fe3aa1df1907e55a1"`);
        await queryRunner.query(`ALTER TABLE "extras_servicio" DROP CONSTRAINT "FK_9b43ecd4a3a08065ac16fa6f35a"`);
        await queryRunner.query(`ALTER TABLE "prorrogas" DROP CONSTRAINT "FK_7b97a28815b0b51ffa0c2cfa508"`);
        await queryRunner.query(`ALTER TABLE "viajes" DROP CONSTRAINT "FK_5e53ccfba23544aa492c4172ad5"`);
        await queryRunner.query(`ALTER TABLE "conversaciones_telegram" DROP CONSTRAINT "FK_d3316c137d51d3d188423f6841b"`);
        await queryRunner.query(`ALTER TABLE "alertas_clientes" DROP CONSTRAINT "FK_c976596ebc7a3fd529701b44beb"`);
        await queryRunner.query(`ALTER TABLE "servicios" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "servicios" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "servicios" ALTER COLUMN "total_base" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "servicios" ALTER COLUMN "total_extras" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "servicios" ALTER COLUMN "total_final" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "servicios" ALTER COLUMN "prorrogas_usadas" SET DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE "conversaciones_telegram" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "conversaciones_telegram" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "servicios" DROP CONSTRAINT "FK_2222734377bc9808ae98cf12ff1"`);
        await queryRunner.query(`ALTER TABLE "conversaciones_telegram" DROP CONSTRAINT "FK_9d05d76273921002e1f60c5d75e"`);
        await queryRunner.query(`ALTER TABLE "alertas_clientes" DROP CONSTRAINT "FK_f8586d2454996457576bb522000"`);
        await queryRunner.query(`ALTER TABLE "clientes" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "clientes" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "alertas_clientes" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "alertas_clientes" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "servicios" DROP CONSTRAINT "FK_86e006c066fd0dd3bdf8657768f"`);
        await queryRunner.query(`ALTER TABLE "empleadas" DROP CONSTRAINT "FK_4dac7fbb10edd9adffa303cf6fc"`);
        await queryRunner.query(`ALTER TABLE "extras_servicio" DROP CONSTRAINT "FK_ddb5a9375897e2c22eddfeb1b08"`);
        await queryRunner.query(`ALTER TABLE "choferes" DROP CONSTRAINT "FK_2dea093853d48942891f276ad9c"`);
        await queryRunner.query(`ALTER TABLE "alertas_clientes" DROP CONSTRAINT "FK_59fbac54f7f7570d04cc2c49a9e"`);
        await queryRunner.query(`ALTER TABLE "usuarios" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "usuarios" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "servicios" DROP CONSTRAINT "FK_1fd705987516f6766736a579a74"`);
        await queryRunner.query(`ALTER TABLE "empleada_fotos" DROP CONSTRAINT "FK_1fb684931383502b5e8cb80f4fc"`);
        await queryRunner.query(`ALTER TABLE "extras_catalogo" DROP CONSTRAINT "FK_c021e5b34c1d635452614ef075c"`);
        await queryRunner.query(`ALTER TABLE "empleadas" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "empleadas" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "extras_servicio" DROP CONSTRAINT "FK_dd3387bba65c6765cae6fa6c5b3"`);
        await queryRunner.query(`ALTER TABLE "extras_catalogo" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "extras_catalogo" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`CREATE UNIQUE INDEX "empleada_fotos_empleada_id_orden_key" ON "empleada_fotos"  ("empleada_id", "orden") `);
        await queryRunner.query(`ALTER TABLE "empleada_fotos" ADD CONSTRAINT "FK_1fb684931383502b5e8cb80f4fc" FOREIGN KEY ("empleada_id") REFERENCES "empleadas"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "extensiones_servicio" ADD CONSTRAINT "FK_27b5b99c53fe3aa1df1907e55a1" FOREIGN KEY ("servicio_id") REFERENCES "servicios"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "extras_servicio" ADD CONSTRAINT "FK_dd3387bba65c6765cae6fa6c5b3" FOREIGN KEY ("extra_catalogo_id") REFERENCES "extras_catalogo"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "extras_servicio" ADD CONSTRAINT "FK_ddb5a9375897e2c22eddfeb1b08" FOREIGN KEY ("registrado_por") REFERENCES "usuarios"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "extras_servicio" ADD CONSTRAINT "FK_9b43ecd4a3a08065ac16fa6f35a" FOREIGN KEY ("servicio_id") REFERENCES "servicios"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prorrogas" ADD CONSTRAINT "FK_7b97a28815b0b51ffa0c2cfa508" FOREIGN KEY ("servicio_id") REFERENCES "servicios"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "choferes" ADD CONSTRAINT "FK_2dea093853d48942891f276ad9c" FOREIGN KEY ("usuario_id") REFERENCES "usuarios"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "viajes" ADD CONSTRAINT "FK_f277fcfb42bf3b6a67bb0281e7b" FOREIGN KEY ("chofer_id") REFERENCES "choferes"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "viajes" ADD CONSTRAINT "FK_5e53ccfba23544aa492c4172ad5" FOREIGN KEY ("servicio_id") REFERENCES "servicios"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "servicios" ADD CONSTRAINT "FK_2222734377bc9808ae98cf12ff1" FOREIGN KEY ("cliente_id") REFERENCES "clientes"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "servicios" ADD CONSTRAINT "FK_1fd705987516f6766736a579a74" FOREIGN KEY ("empleada_id") REFERENCES "empleadas"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "servicios" ADD CONSTRAINT "FK_86e006c066fd0dd3bdf8657768f" FOREIGN KEY ("jefe_id") REFERENCES "usuarios"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversaciones_telegram" ADD CONSTRAINT "FK_9d05d76273921002e1f60c5d75e" FOREIGN KEY ("cliente_id") REFERENCES "clientes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversaciones_telegram" ADD CONSTRAINT "FK_d3316c137d51d3d188423f6841b" FOREIGN KEY ("servicio_id") REFERENCES "servicios"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "alertas_clientes" ADD CONSTRAINT "FK_59fbac54f7f7570d04cc2c49a9e" FOREIGN KEY ("atendida_por") REFERENCES "usuarios"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "alertas_clientes" ADD CONSTRAINT "FK_f8586d2454996457576bb522000" FOREIGN KEY ("cliente_id") REFERENCES "clientes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "alertas_clientes" ADD CONSTRAINT "FK_c976596ebc7a3fd529701b44beb" FOREIGN KEY ("servicio_id") REFERENCES "servicios"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "empleadas" ADD CONSTRAINT "FK_4dac7fbb10edd9adffa303cf6fc" FOREIGN KEY ("usuario_id") REFERENCES "usuarios"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "extras_catalogo" ADD CONSTRAINT "FK_c021e5b34c1d635452614ef075c" FOREIGN KEY ("empleada_id") REFERENCES "empleadas"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "extras_catalogo" DROP CONSTRAINT "FK_c021e5b34c1d635452614ef075c"`);
        await queryRunner.query(`ALTER TABLE "empleadas" DROP CONSTRAINT "FK_4dac7fbb10edd9adffa303cf6fc"`);
        await queryRunner.query(`ALTER TABLE "alertas_clientes" DROP CONSTRAINT "FK_c976596ebc7a3fd529701b44beb"`);
        await queryRunner.query(`ALTER TABLE "alertas_clientes" DROP CONSTRAINT "FK_f8586d2454996457576bb522000"`);
        await queryRunner.query(`ALTER TABLE "alertas_clientes" DROP CONSTRAINT "FK_59fbac54f7f7570d04cc2c49a9e"`);
        await queryRunner.query(`ALTER TABLE "conversaciones_telegram" DROP CONSTRAINT "FK_d3316c137d51d3d188423f6841b"`);
        await queryRunner.query(`ALTER TABLE "conversaciones_telegram" DROP CONSTRAINT "FK_9d05d76273921002e1f60c5d75e"`);
        await queryRunner.query(`ALTER TABLE "servicios" DROP CONSTRAINT "FK_86e006c066fd0dd3bdf8657768f"`);
        await queryRunner.query(`ALTER TABLE "servicios" DROP CONSTRAINT "FK_1fd705987516f6766736a579a74"`);
        await queryRunner.query(`ALTER TABLE "servicios" DROP CONSTRAINT "FK_2222734377bc9808ae98cf12ff1"`);
        await queryRunner.query(`ALTER TABLE "viajes" DROP CONSTRAINT "FK_5e53ccfba23544aa492c4172ad5"`);
        await queryRunner.query(`ALTER TABLE "viajes" DROP CONSTRAINT "FK_f277fcfb42bf3b6a67bb0281e7b"`);
        await queryRunner.query(`ALTER TABLE "choferes" DROP CONSTRAINT "FK_2dea093853d48942891f276ad9c"`);
        await queryRunner.query(`ALTER TABLE "prorrogas" DROP CONSTRAINT "FK_7b97a28815b0b51ffa0c2cfa508"`);
        await queryRunner.query(`ALTER TABLE "extras_servicio" DROP CONSTRAINT "FK_9b43ecd4a3a08065ac16fa6f35a"`);
        await queryRunner.query(`ALTER TABLE "extras_servicio" DROP CONSTRAINT "FK_ddb5a9375897e2c22eddfeb1b08"`);
        await queryRunner.query(`ALTER TABLE "extras_servicio" DROP CONSTRAINT "FK_dd3387bba65c6765cae6fa6c5b3"`);
        await queryRunner.query(`ALTER TABLE "extensiones_servicio" DROP CONSTRAINT "FK_27b5b99c53fe3aa1df1907e55a1"`);
        await queryRunner.query(`ALTER TABLE "empleada_fotos" DROP CONSTRAINT "FK_1fb684931383502b5e8cb80f4fc"`);
        await queryRunner.query(`DROP INDEX "public"."empleada_fotos_empleada_id_orden_key"`);
        await queryRunner.query(`ALTER TABLE "extras_catalogo" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "extras_catalogo" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "extras_servicio" ADD CONSTRAINT "FK_dd3387bba65c6765cae6fa6c5b3" FOREIGN KEY ("extra_catalogo_id") REFERENCES "extras_catalogo"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "empleadas" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "empleadas" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "extras_catalogo" ADD CONSTRAINT "FK_c021e5b34c1d635452614ef075c" FOREIGN KEY ("empleada_id") REFERENCES "empleadas"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "empleada_fotos" ADD CONSTRAINT "FK_1fb684931383502b5e8cb80f4fc" FOREIGN KEY ("empleada_id") REFERENCES "empleadas"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "servicios" ADD CONSTRAINT "FK_1fd705987516f6766736a579a74" FOREIGN KEY ("empleada_id") REFERENCES "empleadas"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuarios" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "usuarios" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "alertas_clientes" ADD CONSTRAINT "FK_59fbac54f7f7570d04cc2c49a9e" FOREIGN KEY ("atendida_por") REFERENCES "usuarios"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "choferes" ADD CONSTRAINT "FK_2dea093853d48942891f276ad9c" FOREIGN KEY ("usuario_id") REFERENCES "usuarios"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "extras_servicio" ADD CONSTRAINT "FK_ddb5a9375897e2c22eddfeb1b08" FOREIGN KEY ("registrado_por") REFERENCES "usuarios"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "empleadas" ADD CONSTRAINT "FK_4dac7fbb10edd9adffa303cf6fc" FOREIGN KEY ("usuario_id") REFERENCES "usuarios"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "servicios" ADD CONSTRAINT "FK_86e006c066fd0dd3bdf8657768f" FOREIGN KEY ("jefe_id") REFERENCES "usuarios"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "alertas_clientes" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "alertas_clientes" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "clientes" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "clientes" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "alertas_clientes" ADD CONSTRAINT "FK_f8586d2454996457576bb522000" FOREIGN KEY ("cliente_id") REFERENCES "clientes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversaciones_telegram" ADD CONSTRAINT "FK_9d05d76273921002e1f60c5d75e" FOREIGN KEY ("cliente_id") REFERENCES "clientes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "servicios" ADD CONSTRAINT "FK_2222734377bc9808ae98cf12ff1" FOREIGN KEY ("cliente_id") REFERENCES "clientes"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversaciones_telegram" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "conversaciones_telegram" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "servicios" ALTER COLUMN "prorrogas_usadas" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "servicios" ALTER COLUMN "total_final" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "servicios" ALTER COLUMN "total_extras" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "servicios" ALTER COLUMN "total_base" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "servicios" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "servicios" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "alertas_clientes" ADD CONSTRAINT "FK_c976596ebc7a3fd529701b44beb" FOREIGN KEY ("servicio_id") REFERENCES "servicios"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversaciones_telegram" ADD CONSTRAINT "FK_d3316c137d51d3d188423f6841b" FOREIGN KEY ("servicio_id") REFERENCES "servicios"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "viajes" ADD CONSTRAINT "FK_5e53ccfba23544aa492c4172ad5" FOREIGN KEY ("servicio_id") REFERENCES "servicios"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prorrogas" ADD CONSTRAINT "FK_7b97a28815b0b51ffa0c2cfa508" FOREIGN KEY ("servicio_id") REFERENCES "servicios"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "extras_servicio" ADD CONSTRAINT "FK_9b43ecd4a3a08065ac16fa6f35a" FOREIGN KEY ("servicio_id") REFERENCES "servicios"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "extensiones_servicio" ADD CONSTRAINT "FK_27b5b99c53fe3aa1df1907e55a1" FOREIGN KEY ("servicio_id") REFERENCES "servicios"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "viajes" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "viajes" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "choferes" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "choferes" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "viajes" ADD CONSTRAINT "FK_f277fcfb42bf3b6a67bb0281e7b" FOREIGN KEY ("chofer_id") REFERENCES "choferes"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prorrogas" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "prorrogas" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "extras_servicio" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "extras_servicio" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "extensiones_servicio" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "extensiones_servicio" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "empleada_fotos" ALTER COLUMN "orden" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "empleada_fotos" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "empleada_fotos" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`CREATE UNIQUE INDEX "empleada_fotos_empleada_id_orden_key" ON "empleada_fotos" USING btree ("empleada_id", "orden") `);
        await queryRunner.query(`ALTER TABLE "servicios" DROP COLUMN "notificacion_extension_enviada"`);
    }

}
